import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fecthAllCategories, fecthAllProducts,fecthProductsByFilters,fecthAllBrands, fecthProductById } from './ProductApi';

const initialState = {
  products: [],
  categories: [],
  brands : [],
  status: 'idle',
  totalItems : 0,
  selectedProduct : null
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fecthAllProductsAsync = createAsyncThunk(
  'product/fetchAllProducts',
  async () => {
    const response = await fecthAllProducts();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fecthProductByIdAsync = createAsyncThunk(
  'product/fecthProductByIdAsync',
  async (id) => {
    const response = await fecthProductById(id);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const fecthProductsByFiltersAsync = createAsyncThunk(
  'product/fecthProductsByFilters',
  async ({filter,sort,pagination}) => {
    const response = await fecthProductsByFilters({filter,sort,pagination});
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);
export const fecthCategoriesAsync = createAsyncThunk(
  'product/fecthCategoriesAsync',
  async () => {
    const response = await fecthAllCategories();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);
export const fecthBrandsAsync = createAsyncThunk(
  'product/fecthBrandsAsync',
  async () => {
    const response = await fecthAllBrands();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const productSlice = createSlice({
  name: 'product',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value += 1;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fecthAllProductsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fecthAllProductsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.products = action.payload;
      })
      .addCase(fecthProductsByFiltersAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fecthProductsByFiltersAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        const {products,totalItems} = action.payload;
        state.products = products;
        state.totalItems = totalItems;
      })
      .addCase(fecthCategoriesAsync.fulfilled, (state, action) => {
        state.categories = action.payload;
      })
      .addCase(fecthBrandsAsync.fulfilled, (state, action) => {
        state.brands = action.payload;
      })
      .addCase(fecthProductByIdAsync.pending, (state, action) => {
        state.status = 'loading';
      })
      .addCase(fecthProductByIdAsync.fulfilled, (state, action) => {
        state.selectedProduct = action.payload;
      });
  },
});

export const { increment} = productSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectAllProducts = (state) => state.product.products;
export const selectTotalItems = (state) => state.product.totalItems;
export const selectAllCategories = (state) => state.product.categories;
export const selectAllBrands = (state) => state.product.brands;
export const selectProductById = (state) => state.product.selectedProduct;

export default productSlice.reducer;
